version: '3'
services:
  web:
    build: .
    ports:
      - "8080:5000"
  db:
    image: mysql:latest
    environment:
      MYSQL_USER: ${DB_USER}
      MYSQL_PASSWORD: ${DB_PASSWORD}
    env_file:
      - .env